<%@ page contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" %>
<%@ taglib prefix="c" uri="/WEB-INF/tld/jakarta-tags-core.tld" %>
<!doctype html>
<html lang="vi"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Quản lý người dùng | KhangGear</title><link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"></head>
<body class="bg-light"><nav class="navbar navbar-dark bg-primary"><div class="container"><a class="navbar-brand" href="${pageContext.request.contextPath}/admin">KhangGear Admin</a><form method="post" action="${pageContext.request.contextPath}/logout"><input type="hidden" name="${_csrf.parameterName}" value="${_csrf.token}"><button class="btn btn-outline-light" type="submit">Đăng xuất</button></form></div></nav>
<main class="container py-4"><div class="d-flex justify-content-between align-items-center gap-3 mb-3"><div><a href="${pageContext.request.contextPath}/admin">Quản trị</a><h1 class="h3 mb-0">Quản lý người dùng</h1></div><a class="btn btn-primary text-nowrap" href="${pageContext.request.contextPath}/admin/user/add">+ Thêm người dùng</a></div>
<c:if test="${not empty message}"><div class="alert alert-success"><c:out value="${message}"/></div></c:if><c:if test="${not empty error}"><div class="alert alert-danger"><c:out value="${error}"/></div></c:if>
<form class="row g-2 mb-3" method="get" action="${pageContext.request.contextPath}/admin/user/list"><div class="col-md-6"><label class="visually-hidden" for="keyword">Tìm người dùng</label><input class="form-control" id="keyword" name="keyword" value="<c:out value='${keyword}'/>" maxlength="254" placeholder="Tìm username hoặc email..."></div><div class="col-auto"><button class="btn btn-secondary" type="submit">Tìm</button></div></form>
<div class="card shadow-sm"><div class="table-responsive"><table class="table table-hover align-middle mb-0"><thead><tr><th>Username</th><th>Email</th><th>Họ tên</th><th>Role</th><th>Trạng thái</th><th>Email</th><th class="text-end">Thao tác</th></tr></thead><tbody><c:choose><c:when test="${empty users.content}"><tr><td colspan="7" class="text-center py-4 text-muted">Không tìm thấy người dùng.</td></tr></c:when><c:otherwise><c:forEach var="account" items="${users.content}"><tr><td><c:out value="${account.username}"/></td><td><c:out value="${account.email}"/></td><td><c:out value="${account.fullName}"/></td><td><span class="badge text-bg-secondary"><c:out value="${account.role}"/></span></td><td><span class="badge ${account.active ? 'text-bg-success' : 'text-bg-danger'}">${account.active ? 'Hoạt động' : 'Đã khóa'}</span></td><td><span class="badge ${account.emailVerified ? 'text-bg-success' : 'text-bg-warning'}">${account.emailVerified ? 'Đã xác minh' : 'Chưa xác minh'}</span></td><td class="text-end text-nowrap"><a class="btn btn-sm btn-outline-primary" href="${pageContext.request.contextPath}/admin/user/edit?id=${account.id}">Sửa</a> <form class="d-inline" method="post" action="${pageContext.request.contextPath}/admin/user/toggle-status"><input type="hidden" name="${_csrf.parameterName}" value="${_csrf.token}"><input type="hidden" name="id" value="${account.id}"><input type="hidden" name="active" value="${not account.active}"><button class="btn btn-sm btn-outline-warning" type="submit">${account.active ? 'Khóa' : 'Mở khóa'}</button></form> <form class="d-inline" method="post" action="${pageContext.request.contextPath}/admin/user/delete" onsubmit="return confirm('Xóa người dùng này?');"><input type="hidden" name="${_csrf.parameterName}" value="${_csrf.token}"><input type="hidden" name="id" value="${account.id}"><button class="btn btn-sm btn-outline-danger" type="submit">Xóa</button></form></td></tr></c:forEach></c:otherwise></c:choose></tbody></table></div></div>
<c:if test="${users.totalPages > 1}"><nav class="mt-3" aria-label="Phân trang"><ul class="pagination"><c:forEach begin="0" end="${users.totalPages - 1}" var="number"><li class="page-item ${number == users.number ? 'active' : ''}"><a class="page-link" href="${pageContext.request.contextPath}/admin/user/list?keyword=${keyword}&page=${number}">${number + 1}</a></li></c:forEach></ul></nav></c:if>
</main></body></html>
