package vn.edu.hcmute.khanggearver2.web;

import java.io.IOException; import java.math.BigDecimal; import java.nio.file.*; import java.util.Locale; import java.util.Map; import java.util.UUID;
import org.springframework.beans.factory.annotation.Value; import org.springframework.context.annotation.Profile; import org.springframework.dao.DataIntegrityViolationException; import org.springframework.stereotype.Controller; import org.springframework.ui.Model; import org.springframework.web.bind.annotation.*; import org.springframework.web.multipart.MultipartFile; import org.springframework.web.servlet.mvc.support.RedirectAttributes;
import vn.edu.hcmute.khanggearver2.domain.Category; import vn.edu.hcmute.khanggearver2.domain.Product; import vn.edu.hcmute.khanggearver2.exception.BusinessRuleException; import vn.edu.hcmute.khanggearver2.service.CategoryService; import vn.edu.hcmute.khanggearver2.service.ProductService;

@Controller @Profile("!foundation") @RequestMapping("/admin/product") public class ProductAdminController {
 private static final long MAX_IMAGE=2*1024*1024L; private final ProductService products; private final CategoryService categories; private final Path uploadRoot;
 public ProductAdminController(ProductService p,CategoryService c,@Value("${app.product-upload-dir:uploads/products}") String root){products=p;categories=c;uploadRoot=Paths.get(root).toAbsolutePath().normalize();}
 @GetMapping({"","/list"}) String list(@RequestParam(defaultValue="") String keyword,@RequestParam(required=false) Long categoryId,@RequestParam(required=false) Boolean active,@RequestParam(defaultValue="0") int page,Model model){model.addAttribute("products",products.search(keyword,categoryId,active,org.springframework.data.domain.PageRequest.of(Math.max(0,page),6,org.springframework.data.domain.Sort.by("createdAt").descending())));model.addAttribute("keyword",keyword);model.addAttribute("categoryId",categoryId);model.addAttribute("active",active);model.addAttribute("categories",categories.search("",org.springframework.data.domain.PageRequest.of(0,100,org.springframework.data.domain.Sort.by("name"))));return "admin/product/list";}
 @GetMapping("/add") String add(Model model){if(!model.containsAttribute("product"))model.addAttribute("product",new Product());return form(model,"admin/product/add");}
 @PostMapping("/add") String add(@RequestParam(required=false) String name,@RequestParam(required=false) String description,@RequestParam(required=false) String price,@RequestParam(required=false) String stock,@RequestParam(required=false) Long categoryId,@RequestParam(required=false) Boolean active,@RequestParam(required=false) MultipartFile image,Model model,RedirectAttributes flash){Product p=read(name,description,price,stock,categoryId,active);String error=validate(p,image);if(error!=null)return error(model,p,error,"admin/product/add");String file=null;try{file=store(image);p.setImage(file);p.setCategory(categories.getById(categoryId));products.create(p);flash.addFlashAttribute("message","Them san pham thanh cong.");return "redirect:/admin/product/list";}catch(RuntimeException|IOException e){delete(file);return error(model,p,message(e,"Khong the them san pham."),"admin/product/add");}}
 @GetMapping("/edit") String edit(@RequestParam Long id,Model model){model.addAttribute("product",products.getById(id));return form(model,"admin/product/edit");}
 @PostMapping("/edit") String edit(@RequestParam Long id,@RequestParam(required=false) String name,@RequestParam(required=false) String description,@RequestParam(required=false) String price,@RequestParam(required=false) String stock,@RequestParam(required=false) Long categoryId,@RequestParam(required=false) Boolean active,@RequestParam(required=false) MultipartFile image,Model model,RedirectAttributes flash){Product p=read(name,description,price,stock,categoryId,active);String error=validate(p,image);if(error!=null)return error(model,p,error,"admin/product/edit");String file=null;try{Product old=products.getById(id);file=store(image);p.setImage(file!=null?file:old.getImage());p.setCategory(categories.getById(categoryId));products.update(id,p);flash.addFlashAttribute("message","Cap nhat san pham thanh cong.");return "redirect:/admin/product/list";}catch(RuntimeException|IOException e){delete(file);return error(model,p,message(e,"Khong the cap nhat san pham."),"admin/product/edit");}}
 @PostMapping("/delete") String delete(@RequestParam Long id,RedirectAttributes flash){try{products.deleteOrDeactivate(id);flash.addFlashAttribute("message","Xoa san pham thanh cong.");}catch(BusinessRuleException e){flash.addFlashAttribute("error",e.getMessage());}catch(DataIntegrityViolationException e){flash.addFlashAttribute("error","Khong the xoa san pham dang duoc su dung.");}catch(RuntimeException e){flash.addFlashAttribute("error","Khong the xoa san pham.");}return "redirect:/admin/product/list";}
 @PostMapping("/toggle-status") String toggle(@RequestParam Long id,@RequestParam boolean active,RedirectAttributes flash){products.toggleActive(id,active);flash.addFlashAttribute("message",active?"Da mo ban san pham.":"Da khoa san pham.");return "redirect:/admin/product/list";}
 private String form(Model model,String view){model.addAttribute("categories",categories.search("",org.springframework.data.domain.PageRequest.of(0,100,org.springframework.data.domain.Sort.by("name"))));return view;}
 private Product read(String name,String description,String price,String stock,Long categoryId,Boolean active){Product p=new Product();p.setName(name);p.setDescription(description);p.setActive(Boolean.TRUE.equals(active));try{p.setPrice(new BigDecimal(price==null?"-1":price));}catch(Exception e){p.setPrice(BigDecimal.valueOf(-1));}try{p.setStock(Integer.valueOf(stock==null?"-1":stock));}catch(Exception e){p.setStock(-1);}if(categoryId!=null){try{p.setCategory(categories.getById(categoryId));}catch(Exception ignored){}}return p;}
 private String validate(Product p,MultipartFile image){if(p.getName()==null||p.getName().trim().isEmpty())return "Ten san pham la bat buoc.";if(p.getPrice()==null||p.getPrice().compareTo(BigDecimal.ZERO)<0)return "Gia phai la so khong am.";if(p.getStock()==null||p.getStock()<0)return "Ton kho phai la so nguyen khong am.";if(p.getCategory()==null)return "Danh muc khong hop le.";if(image!=null&&!image.isEmpty()){String n=image.getOriginalFilename()==null?"":image.getOriginalFilename().toLowerCase(Locale.ROOT);String t=image.getContentType()==null?"":image.getContentType().toLowerCase(Locale.ROOT);if(image.getSize()>MAX_IMAGE||!(t.equals("image/png")||t.equals("image/jpeg")||t.equals("image/webp"))||!(n.endsWith(".png")||n.endsWith(".jpg")||n.endsWith(".jpeg")||n.endsWith(".webp")))return "Anh chi chap nhan PNG, JPG/JPEG hoac WebP va toi da 2 MB.";}return null;}
 private String store(MultipartFile f)throws IOException{if(f==null||f.isEmpty())return null;String n=f.getOriginalFilename();String ext=n.substring(n.lastIndexOf('.')).toLowerCase(Locale.ROOT);Files.createDirectories(uploadRoot);Path out=uploadRoot.resolve(UUID.randomUUID()+ext).normalize();if(!out.getParent().equals(uploadRoot))throw new IOException("Invalid upload path");Files.write(out,f.getBytes());return out.getFileName().toString();}
 private void delete(String n){if(n!=null)try{Files.deleteIfExists(uploadRoot.resolve(n).normalize());}catch(IOException ignored){}}
 private String error(Model m,Product p,String e,String view){m.addAttribute("product",p);m.addAttribute("error",e);return form(m,view);}
 private String message(Exception e,String fallback){return e.getMessage()==null?fallback:e.getMessage();}
}
