spring.application.name=KhangGearVer2
spring.datasource.url=${SQLSERVER_URL:}
spring.datasource.username=${SQLSERVER_USERNAME:}
spring.datasource.password=${SQLSERVER_PASSWORD:}
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true
