package vn.edu.hcmute.khanggearver2.service.impl;
import java.math.BigDecimal;
import org.springframework.context.annotation.Profile; import org.springframework.data.domain.Page; import org.springframework.data.domain.Pageable; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional;
import vn.edu.hcmute.khanggearver2.domain.Product; import vn.edu.hcmute.khanggearver2.exception.BusinessRuleException; import vn.edu.hcmute.khanggearver2.exception.ResourceNotFoundException; import vn.edu.hcmute.khanggearver2.repository.OrderItemRepository; import vn.edu.hcmute.khanggearver2.repository.ProductRepository; import vn.edu.hcmute.khanggearver2.service.ProductService;
@Service @Profile("!foundation") public class ProductServiceImpl implements ProductService {
 private final ProductRepository products; private final OrderItemRepository items; public ProductServiceImpl(ProductRepository p,OrderItemRepository i){products=p;items=i;}
 @Transactional public Product create(Product input){normalize(input);return products.save(input);} @Transactional(readOnly=true) public Product getById(Long id){return products.findById(id).orElseThrow(()->new ResourceNotFoundException("Khong tim thay san pham"));}
 @Transactional public Product update(Long id,Product input){Product current=getById(id);normalize(input);current.setName(input.getName());current.setDescription(input.getDescription());current.setPrice(input.getPrice());current.setStock(input.getStock());current.setImage(input.getImage());current.setActive(input.getActive());current.setCategory(input.getCategory());return products.save(current);}
 @Transactional public void deleteOrDeactivate(Long id){Product product=getById(id);if(items.existsByProductId(id)){product.setActive(false);products.save(product);throw new BusinessRuleException("Khong the xoa san pham vi san pham da ton tai trong don hang. San pham da duoc khoa.");}products.delete(product);}
 @Transactional public Product toggleActive(Long id,boolean active){Product product=getById(id);product.setActive(active);return products.save(product);}
 @Transactional(readOnly=true) public Page<Product> search(String keyword,Long categoryId,Boolean active,Pageable pageable){return products.search(keyword==null?"":keyword.trim(),categoryId,active,pageable);}
 private void normalize(Product p){if(p.getName()==null||p.getName().trim().isEmpty())throw new IllegalArgumentException("Ten san pham la bat buoc");if(p.getPrice()==null||p.getPrice().compareTo(BigDecimal.ZERO)<0)throw new IllegalArgumentException("Gia phai lon hon hoac bang 0");if(p.getStock()==null||p.getStock()<0)throw new IllegalArgumentException("Ton kho phai la so nguyen khong am");p.setName(p.getName().trim());if(p.getDescription()!=null)p.setDescription(p.getDescription().trim());if(p.getActive()==null)p.setActive(true);}
}
