import { useEffect, useState } from 'react'
import { Link, Route, Routes, useLocation, useNavigate, useSearchParams } from 'react-router-dom'
import { ArrowRight, ChevronDown, Grid2X2, Menu, Search, ShoppingBag, SlidersHorizontal, X } from 'lucide-react'
import { getCategories, getFeatured, getProducts, mediaUrl } from './api.js'

const fallbackImage = 'https://images.unsplash.com/photo-1593640408182-31c70c8268f5?auto=format&fit=crop&w=900&q=80'

function Header({ onSearch }) {
  const [query, setQuery] = useState('')
  const [open, setOpen] = useState(false)
  const submit = (event) => { event.preventDefault(); onSearch(query) }
  return <header className="kg-header"><div className="kg-shell kg-header-row"><button className="kg-icon-button kg-mobile-only" onClick={() => setOpen(!open)} aria-label="Mở menu">{open ? <X size={20} /> : <Menu size={20} />}</button><Link className="kg-brand" to="/"><span className="kg-brand-mark">K</span><span>Khang<span>Gear</span><small>TECH FOR YOUR SETUP</small></span></Link><form className="kg-search" onSubmit={submit}><Search size={18} /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Tìm thiết bị, phụ kiện, gaming gear..." /><button>Tìm</button></form><div className="kg-actions"><Link to="/account">Tài khoản <ChevronDown size={14} /></Link><Link className="kg-bag" to="/cart"><ShoppingBag size={19} /><span>0</span></Link></div></div><nav className={`kg-nav ${open ? 'kg-nav-open' : ''}`}><div className="kg-shell"><Link to="/">Trang chủ</Link><Link to="/products">Sản phẩm</Link><a href="/#categories">Danh mục</a><Link to="/orders">Đơn hàng của tôi</Link></div></nav></header>
}

function ProductCard({ product }) { return <article className="kg-product-card"><Link to={`/products/${product.id}`} className="kg-product-image"><img src={mediaUrl(product.imageUrl) || fallbackImage} alt={product.name} onError={(event) => { event.currentTarget.src = fallbackImage }} />{product.stock < 5 && <b>Sắp hết</b>}</Link><div className="kg-product-body"><small>{product.categoryName}</small><Link to={`/products/${product.id}`}><h3>{product.name}</h3></Link><div className="kg-product-foot"><strong>{new Intl.NumberFormat('vi-VN').format(product.price)} đ</strong><span>{product.stock > 0 ? `Còn ${product.stock}` : 'Hết hàng'}</span></div></div></article> }
// eslint-disable-next-line no-unused-vars
function Home({ onSearch }) { const [featured, setFeatured] = useState({ content: [] }); const [categories, setCategories] = useState([]); useEffect(() => { Promise.all([getFeatured(), getCategories()]).then(([p, c]) => { setFeatured(p); setCategories(c) }).catch(() => {}) }, []); return <><section className="kg-hero"><div className="kg-hero-copy"><span className="kg-eyebrow">KHANGGEAR CHOICE 2026</span><h1>Thiết bị tốt cho <em>mọi setup.</em></h1><p>Chọn đúng công nghệ để làm việc mượt hơn, chơi đã hơn và tận hưởng từng khoảnh khắc.</p><div className="kg-hero-actions"><Link className="kg-button kg-button-primary" to="/products">Khám phá sản phẩm <ArrowRight size={18} /></Link><a className="kg-button kg-button-ghost" href="#categories">Xem danh mục</a></div></div></section><section className="kg-trust"><div>Giao nhanh toàn quốc<small>Đóng gói kỹ, theo dõi dễ dàng</small></div><div>Bảo hành chính hãng<small>Đồng hành suốt quá trình sử dụng</small></div><div>Đổi trả minh bạch<small>Hỗ trợ nhanh khi cần thiết</small></div><div>Tư vấn thật lòng<small>Chọn đúng nhu cầu, không chọn dư</small></div></section><section id="categories" className="kg-section kg-section-muted"><div className="kg-section-heading"><div><span className="kg-eyebrow">DANH MỤC NỔI BẬT</span><h2>Tìm theo cách bạn dùng công nghệ</h2></div><Link to="/products">Khám phá <ArrowRight size={16} /></Link></div><div className="kg-category-grid">{categories.map((category) => <Link key={category.id} to={`/products?categoryId=${category.id}`} className="kg-category-card"><Grid2X2 size={28} /><h3>{category.name}</h3><span>Xem sản phẩm <ArrowRight size={14} /></span></Link>)}</div></section><section className="kg-section"><div className="kg-section-heading"><div><span className="kg-eyebrow">ĐƯỢC CHỌN CHO BẠN</span><h2>Sản phẩm nổi bật</h2></div><Link to="/products">Xem tất cả <ArrowRight size={16} /></Link></div><div className="kg-product-grid">{featured.content.map((product) => <ProductCard key={product.id} product={product} />)}</div></section></> }

function Products({ initialQuery = '' }) { const [params, setParams] = useSearchParams(); const [data, setData] = useState({ content: [] }); const [categories, setCategories] = useState([]); const [loading, setLoading] = useState(true); const [filters, setFilters] = useState({ keyword: params.get('keyword') || initialQuery, categoryId: params.get('categoryId') || '', inStock: false, sort: 'newest' }); useEffect(() => { getCategories().then(setCategories).catch(() => {}) }, []); useEffect(() => { setLoading(true); getProducts(filters).then(setData).catch(() => setData({ content: [] })).finally(() => setLoading(false)) }, [filters]); const update = (name, value) => { const next = { ...filters, [name]: value }; setFilters(next); const query = Object.fromEntries(Object.entries(next).filter(([, v]) => v !== '' && v !== false)); setParams(query) }; return <section className="kg-section kg-products-page"><div className="kg-section-heading"><div><span className="kg-eyebrow">KHANGGEAR STORE</span><h1>Sản phẩm công nghệ</h1><p>Chọn theo nhu cầu, ngân sách và tình trạng tồn kho thực tế.</p></div></div><div className="kg-catalog-layout"><aside className="kg-filter-panel"><h2><SlidersHorizontal size={18} /> Lọc sản phẩm</h2><label>Tìm kiếm<input value={filters.keyword} onChange={(e) => update('keyword', e.target.value)} placeholder="Tên sản phẩm..." /></label><label>Danh mục<select value={filters.categoryId} onChange={(e) => update('categoryId', e.target.value)}><option value="">Tất cả danh mục</option>{categories.map((c) => <option value={c.id} key={c.id}>{c.name}</option>)}</select></label><label>Giá từ<input type="number" min="0" onChange={(e) => update('minPrice', e.target.value)} /></label><label>Đến<input type="number" min="0" onChange={(e) => update('maxPrice', e.target.value)} /></label><label className="kg-check"><input type="checkbox" checked={filters.inStock} onChange={(e) => update('inStock', e.target.checked)} /> Chỉ hiện còn hàng</label></aside><div className="kg-catalog-results"><div className="kg-results-toolbar"><span>{data.totalElements || 0} sản phẩm</span><select value={filters.sort} onChange={(e) => update('sort', e.target.value)}><option value="newest">Mới nhất</option><option value="price-asc">Giá thấp đến cao</option><option value="price-desc">Giá cao đến thấp</option><option value="name">Tên A-Z</option></select></div>{loading ? <div className="kg-empty">Đang tải sản phẩm...</div> : data.content.length ? <div className="kg-product-grid">{data.content.map((p) => <ProductCard key={p.id} product={p} />)}</div> : <div className="kg-empty">Chưa có sản phẩm phù hợp.</div>}</div></div></section> }

function Placeholder({ title }) { return <section className="kg-section kg-empty-page"><span className="kg-eyebrow">KHANGGEAR</span><h1>{title}</h1><p>Khu vực này sẽ được kết nối trong luồng tài khoản và thương mại điện tử.</p><Link className="kg-button kg-button-primary" to="/products">Tiếp tục mua sắm <ArrowRight size={18} /></Link></section> }
export default function App() { const location = useLocation(); const navigate = useNavigate(); const [query, setQuery] = useState(''); const search = (value) => { setQuery(value); navigate(`/products?keyword=${encodeURIComponent(value)}`) }; return <div className="kg-app"><Header onSearch={search} /><main>{location.pathname === '/' ? <Home onSearch={search} /> : <Routes><Route path="/products" element={<Products initialQuery={query} />} /><Route path="/account" element={<Placeholder title="Tài khoản của tôi" />} /><Route path="/orders" element={<Placeholder title="Đơn hàng của tôi" />} /><Route path="/cart" element={<Placeholder title="Giỏ hàng" />} /><Route path="*" element={<Products />} /></Routes>}</main><footer className="kg-footer"><div className="kg-shell"><strong>KhangGear</strong><span>Thiết bị tốt cho mọi setup.</span><span>© 2026 KhangGear</span></div></footer></div> }
