import { useEffect, useState } from 'react'
import { Link } from 'react-router-dom'
import { ArrowRight, Minus, Plus, Trash2 } from 'lucide-react'
import { cancelOrder, checkout, getCart, getOrders, getProfile, mediaUrl, removeFromCart, updateCart } from './api.js'

const money = (value) => new Intl.NumberFormat('vi-VN').format(value || 0) + ' đ'
function CartPage() { const [cart, setCart] = useState({ items: [], total: 0 }); const [error, setError] = useState(''); useEffect(() => { getCart().then(setCart).catch(() => setError('Vui lòng đăng nhập để sử dụng giỏ hàng.')) }, []); const change = (id, quantity) => updateCart(id, quantity).then(setCart).catch((e) => setError(e.response?.data?.message || 'Không thể cập nhật giỏ hàng.')); return <section className="kg-section"><div className="kg-section-heading"><div><span className="kg-eyebrow">KHANGGEAR CART</span><h1>Giỏ hàng của bạn</h1></div></div>{error && <div className="kg-alert">{error}</div>}{cart.items.length ? <div className="kg-cart-layout"><div>{cart.items.map((item) => <article className="kg-cart-line" key={item.productId}><img src={mediaUrl(item.imageUrl)} alt={item.name} /><div><h3>{item.name}</h3><small>{money(item.unitPrice)}</small><div className="kg-quantity"><button onClick={() => item.quantity > 1 && change(item.productId, item.quantity - 1)}><Minus size={14} /></button><span>{item.quantity}</span><button onClick={() => change(item.productId, item.quantity + 1)}><Plus size={14} /></button><button className="kg-delete" onClick={() => removeFromCart(item.productId).then(setCart)}><Trash2 size={15} /></button></div></div><strong>{money(item.lineTotal)}</strong></article>)}</div><aside className="kg-summary"><h2>Tóm tắt</h2><div>Tạm tính <strong>{money(cart.total)}</strong></div><Link className="kg-button kg-button-primary" to="/checkout">Tiến hành thanh toán <ArrowRight size={17} /></Link></aside></div> : <div className="kg-empty">Giỏ hàng đang trống.<br /><Link className="kg-button kg-button-primary" to="/products">Khám phá sản phẩm</Link></div>}</section> }
function CheckoutPage() { const [form, setForm] = useState({ receiverName: '', phone: '', email: '', shippingAddress: '', note: '', paymentMethod: 'COD' }); const [error, setError] = useState(''); const submit = (event) => { event.preventDefault(); setError(''); checkout(form).then((id) => { window.location.href = `/orders?success=${id}` }).catch((e) => setError(e.response?.data?.message || 'Không thể tạo đơn hàng.')) }; return <section className="kg-section kg-checkout"><div className="kg-section-heading"><div><span className="kg-eyebrow">CHECKOUT</span><h1>Thông tin giao hàng</h1></div></div>{error && <div className="kg-alert">{error}</div>}<form onSubmit={submit} className="kg-form"><label>Họ tên người nhận<input required value={form.receiverName} onChange={(e) => setForm({ ...form, receiverName: e.target.value })} /></label><label>Số điện thoại<input required pattern="[0-9+(). -]{8,20}" value={form.phone} onChange={(e) => setForm({ ...form, phone: e.target.value })} /></label><label>Email<input required type="email" value={form.email} onChange={(e) => setForm({ ...form, email: e.target.value })} /></label><label>Địa chỉ giao hàng<textarea required value={form.shippingAddress} onChange={(e) => setForm({ ...form, shippingAddress: e.target.value })} /></label><label>Ghi chú<textarea value={form.note} onChange={(e) => setForm({ ...form, note: e.target.value })} /></label><label>Thanh toán<select value={form.paymentMethod} onChange={(e) => setForm({ ...form, paymentMethod: e.target.value })}><option value="COD">Thanh toán khi nhận hàng</option><option value="BANK_TRANSFER">Chuyển khoản ngân hàng</option></select></label><button className="kg-button kg-button-primary" type="submit">Đặt hàng</button></form></section> }
function AccountPage() { const [profile, setProfile] = useState(null); useEffect(() => { getProfile().then(setProfile).catch(() => {}) }, []); return <section className="kg-section kg-empty-page"><span className="kg-eyebrow">ACCOUNT</span><h1>Tài khoản của tôi</h1>{profile ? <p>Xin chào <strong>{profile.fullName || profile.username}</strong><br />{profile.email}</p> : <p>Vui lòng đăng nhập để xem thông tin tài khoản.</p>}</section> }
function OrdersPage() { const [orders, setOrders] = useState([]); useEffect(() => { getOrders().then(setOrders).catch(() => {}) }, []); return <section className="kg-section"><div className="kg-section-heading"><div><span className="kg-eyebrow">ACCOUNT</span><h1>Đơn hàng của tôi</h1></div></div>{orders.length ? <div className="kg-order-list">{orders.map((order) => <article key={order.id} className="kg-order-card"><div><b>#{order.id}</b><span>{order.status}</span><p>{order.products.join(', ')}</p></div><strong>{money(order.totalAmount)}</strong>{(order.status === 'PENDING' || order.status === 'CONFIRMED') && <button onClick={() => cancelOrder(order.id).then((updated) => setOrders(orders.map((item) => item.id === updated.id ? updated : item)))}>Hủy đơn</button>}</article>)}</div> : <div className="kg-empty">Chưa có đơn hàng.</div>}</section> }
export { AccountPage, CartPage, CheckoutPage, OrdersPage }
